blog/urls.py
from django.urls import path

from .views import ProfileView

app_name = 'blog'
urlpatterns = [
    path('', ProfileView.as_view(), name='index'),
]

gallery/urls.py
from django.urls import path

from .views import image_id, VectorDrawingCreateView, GalleryView, GalleryByTagView

app_name = 'gallery'
urlpatterns = [
    #path('', index, name='index'),
    path('', GalleryView.as_view(), name='index'),
    path('add/', VectorDrawingCreateView.as_view(), name='add'),
    path('<int:pk>/', image_id, name='image_id'),
    path('<str:tag>/', GalleryByTagView.as_view(), name='by_tag')
    #path('<str:tag>/', by_tag, name='by_tag'),
]

site_portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView

from . import settings

urlpatterns = [
    path('', include('blog.urls', namespace='blog')),
    path('gallery/', include('gallery.urls', namespace='gallery')),
    path('admin/', admin.site.urls),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    path('social/', include('social_django.urls', namespace='social')),
]

if settings.DEBUG:
    # urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)                      

blog/models.py
from django.contrib.auth.models import User
from django.db import models


class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    info = models.TextField(null=True, blank=True)
    social_links = models.TextField(null=True, blank=True)

    def set_links(self, x):
        self.social_links = ";".join(x)

    def get_links(self):
        return self.social_links.split(';')

gallery/models.py
from django.contrib.auth.models import User
from django.db import models


class Tag(models.Model):
    title = models.CharField(
        max_length=50, verbose_name='Название', unique=True)

    class Meta:
        verbose_name_plural = 'Теги'
        verbose_name = 'Тег'
        ordering = ['title']

    def __str__(self):
        return self.title


class VectorDrawing(models.Model):
    title = models.CharField(max_length=50, verbose_name='Название')
    description = models.TextField(null=True, verbose_name='Описание')
    published = models.DateTimeField(
        auto_now_add=True, db_index=True, verbose_name='Дата публикации')
    image = models.ImageField(
        verbose_name='Изображение',
        upload_to='gallery/'
    )
    vector_file = models.FileField(
        upload_to='vector_files/', null=True, blank=True, verbose_name='Векторный рисунок')
    tags = models.ManyToManyField(
        Tag, verbose_name='Теги', related_name='entries', blank=True)

    class Meta:
        verbose_name_plural = 'Векторные рисунки'
        verbose_name = 'Векторный рисунок'
        ordering = ['-published']

    def __str__(self):
        return self.title


class Comment(models.Model):
    author = models.OneToOneField(User, on_delete=models.CASCADE)
    message = models.TextField(max_length=500)
    vector_drawing = models.ForeignKey(
        VectorDrawing,
        related_name="comment",
        on_delete=models.CASCADE,
    )

gallery/forms.py
from django import forms

from .models import VectorDrawing


class VectorDrawingForm(forms.ModelForm):
    new_tags = forms.CharField(
        label='Новые теги', help_text='Укажите новые теги через ";"', required=False)

    class Meta:
        model = VectorDrawing
        fields = ('title', 'description', 'image', 'tags', 'new_tags')

blog/views.py
from django.contrib.auth.models import User
from django.shortcuts import render
from django.views.generic.base import TemplateView

from .models import Profile

class ProfileView(TemplateView):
    template_name = 'blog/index.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['profile'] = Profile.objects.get(user=User.objects.get(username='Tina'))
        return context

gallery/views.py
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render, redirect
from django.urls import reverse_lazy, reverse
from django.views.generic.edit import CreateView
from django.views.generic.list import ListView

from .forms import VectorDrawingForm
from .models import VectorDrawing, Tag


class GalleryView(ListView):
    template_name = 'gallery/index.html'
    model = VectorDrawing
    context_object_name = 'images'
    paginate_by = 6


class GalleryByTagView(ListView):
    template_name = 'gallery/index.html'
    context_object_name = 'images'
    paginate_by = 6

    def get_queryset(self):
        return VectorDrawing.objects.filter(tags__title=self.kwargs['tag'])


class VectorDrawingCreateView(LoginRequiredMixin, PermissionRequiredMixin, CreateView):
    template_name = 'gallery/add.html'
    form_class = VectorDrawingForm
    success_url = reverse_lazy('gallery:index')
    login_url = "/login"
    permission_required = ('gallery.add_vectordrawing')
    raise_exception = True
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['tags'] = Tag.objects.all()
        return context

    def form_valid(self, form):
        """If the form is valid, save the associated model."""
        self.object = form.save()
        if not self.request.POST.get('new_tags') == '':
            t = []
            new_tag_list = self.request.POST.get('new_tags').split(';')
            if new_tag_list:
                for tag in new_tag_list:
                    t.append(Tag.objects.create(title=tag))
                for tag in t:
                    if not tag in self.object.tags.all():
                        self.object.tags.add(tag)
        return redirect(self.success_url)


def image_id(request, pk):
    success_url = reverse('gallery:index')
    if request.method == 'POST':
        if not 'delete_image' in request.POST:
            image = VectorDrawing.objects.get(id=pk)
            image.title = request.POST.get('title')
            image.description = request.POST.get('description')
            tag_list = []
            for tag in request.POST.getlist('tags'):
                tag_list.append(Tag.objects.get(title=tag))
            for tag in request.POST.getlist('new_tags'):
                tag_list.append(Tag.objects.get(title=tag))
            image.tags.set(tag_list)
            image.save()
            return redirect('gallery:image_id', pk=pk)
        image = VectorDrawing.objects.get(id=pk)
        for tag in image.tags.all():
            if tag.entries.all().count() == 1:
                tag.delete()
        image.delete()
        return redirect(success_url)
    image = VectorDrawing.objects.get(id=pk)
    tags = Tag.objects.all()
    context = {
        'image': image,
        'tags': tags,
    }
    return render(request, 'gallery/image_id.html', context)

blog/templates/blog/index.html
{% extends "gallery/base.html" %}
{% block title %}Профиль{% endblock %}
{% block content %}
<div class="about_me">
    {% if user.is_authenticated %}
    <span>
        {% if user.get_full_name %}
        {{ user.get_full_name }}
        {% else %}
        {{ user.get_username }}
        {% endif %}
        {% else %}
        Гость
        {% endif %}
    </span>
    {{ profile.info }}
    <p>Связь со мной:</p>
    {% for link in profile.get_links %}
    <p><a href="{{ link }}">{{ link }}</a></p>
    {%endfor%}
</div>
{% endblock %}

gallery/templates/gallery/add.html
{% extends "gallery/base.html" %}
{% block title %}Добавление работы{% endblock %}
{% block content %}
<div class="add">
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Добавить</button>
    </form>
</div>
{% endblock %}

gallery/templates/gallery/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'gallery/style.css' %}">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Open+Sans+Condensed:wght@300&display=swap" rel="stylesheet">
    <title>{% block title %}Главная{% endblock %}</title>
</head>

<body>
    <header>
        
        <nav>
            <a class="nav_button" href="{% url 'blog:index' %}">Обо мне</a>
            <a class="nav_button" href="{% url 'gallery:index' %}">Галерея</a>
            <a class="nav_button" href="{% url 'gallery:add' %}">Добавить работу</a>
            {% if user.is_authenticated %}
                <a class="nav_button" href="{% url 'logout' %}">Выход</a>
            {% else %}
                <a class="nav_button" href="{% url 'login' %}">Войти</a>
            {% endif %}
            
            
        </nav>
        {% block pagename %}{% endblock %}
    </header>
    <main>
        
            {% block content %}
            {% endblock %}

    </main>

</body>

</html>

gallery/templates/gallery/image_id.html
{% extends "gallery/base.html" %}
{% block title %}Редактирование работы{% endblock %}
{% block content %}
<div class="image_id">
    <img src="{{ image.description }}">
</div>
{% if 'gallery.change_vectordrawing' in perms %}
<div class="change_fields">
    <form method="POST">
        {% csrf_token %}
        <label>Название работы:</label>
        <input type="text" value="{{ image.title }}" name="title">
        <label>Описание:</label>
        <textarea name="description">{{ image.description }}</textarea>
        <label>Теги работы:</label>
        <select multiple="multiple" name="tags">
            {% for tag in image.tags.all %}
            <option>{{ tag.title }}</option>
            {% endfor %}
        </select>

        <label>Существующие теги:</label>
        <select multiple="multiple" name="new_tags">
            {% for tag in tags %}
            <option>{{ tag.title }}</option>
            {% endfor %}
        </select>
        <p>
            <button type="submit">Изменить</button>
            <button type="submit" name="delete_image">Удалить</button>
        </p>
    </form>
</div>
{% endif %}


{% endblock %}

gallery/templates/gallery/index.html
{% extends "gallery/base.html" %}
{% block title %}Галеря{% endblock %}
{% block content %}

<div class="b-flex">
    {% if page_obj.has_previous %}
    <div class="pagination_previous">
        <!-- <a href="?page=1">first</a> -->
        <div class="pagin">
            <a href="?page={{ page_obj.previous_page_number }}">&lang;</a>
        </div>
    </div>
    {% else %}
    <div class="pagination_previous_plug">
        <div class="pagin_plug">
            <a href="#">&lang;</a>
        </div>
    </div>
    {% endif %}
    <div class="content">
        {% for image in images %}
        <figure>
            <a href="{% url 'gallery:image_id' image.id %}"><img src="{{ image.description }}"></a>
            <figcaption>
                <!-- Название работы: {{ image.title }}
                    Описание: {{ image.description }} -->
                {% for tag in image.tags.all %}
                <div class="tag">
                    <a href="{% url 'gallery:by_tag' tag.title %}"> {{ tag.title }} </a>
                </div>
                {% endfor %}
                <!-- 
                    Дата публикации: {{ image.published|date:"d.m.Y H:i:s" }} -->
            </figcaption>
        </figure>
        {% endfor %}
    </div>
    {% if page_obj.has_next %}
    <div class="pagination_next">
        <div class="pagin">
            <a href="?page={{ page_obj.next_page_number }}">&rang;</a>
            <!-- <a href="?page={{ page_obj.paginator.num_pages }}">last</a> -->
        </div>
    </div>
    {% else %}
    <div class="pagination_next_plug">
        <div class="pagin_plug">
            <a href="#">&rang;</a>
        </div>
    </div>
    {% endif %}
</div>

{% endblock %}